### ISSUE TITLE
Can't select any user but "Family Friendly"

### ISSUE THREAD

**Issue by CatmanIX** [japanesemediamanager/plexplugin#13]
These are the users I have setup:

![JMM Users](http://i.imgur.com/aExqlgQ.png)

These are the users the plex plugin shows:

![Plex Users](http://i.imgur.com/Ph2uIa5.png)

Selecting any of the "User x" profiles, or the "Default" one don't work. they all just say Invalid User when trying to actually launch the channel.

![Invalid](http://i.imgur.com/5acEXQC.png)

I've tried shutting down and relaunching everything, but there's no change.

Any idea how to get this working?

**Comment by AreFinstad** [comment]
its true i guess, we cant type in our user names, we should be able to either type the usernames in and it will save it in the config files for us or have it read the JMM settings and show all users that is around on JMM or Plex Server Start, this would need a check on every start tho.

**Comment by CatmanIX** [comment]
I would have assumed that the plex plugin should already have a way to identify what users are setup on the server, otherwise does that not make the plugin completely non-functional and useless? It can't do anything if it's can't  connect to a user, and if it can't do anything than what even is the point of it?

Does no one else use this plugin?

**Comment by AreFinstad** [comment]
we do use the plugin... but im guessing most of us are using the Default user.
seeings as you renames yours it might have something to do with it. 

only reason you can select the Family user is because you still have an user in JMM named that. 
you can always make another user called default.... User 3-10 should also work i guess (not tried it myself)

ATM the plex app does not read what you have and does not allow input of another name, therefore can only access users named as the drop list it has.

obv something that needs fixing.

**Comment by maxpiva** [comment]
The main problem, is plex plugin preferences need to be hardcoded. The user 1… 2 …3 are in fact, hardcoded, only thing important, is the user id. Since you probably delete de default user, user id 1 do not exist anymore. 
There is no nice way to fix this, probably I could regenerate plex anime plugin preferences, but plex server and jmm server may or may not reside in the same server. 

I could do a button that regenerate the user profile preferences, and the user should move that preferences to the plex plugin directory.

**Comment by AreFinstad** [comment]
sooo there is no way for the plugin to just read from the setting file we already have for the plugin? well that sucks :/

if there was a choice for having just One JMM user using the Plex plugin over being able to choose from the drop list i would rather have the one TBH.
too bad it cant be fixed tho :/

oh and BTW: have you guys looked into EMBY? http://emby.media/
the transcoding isnt as effective (but it doesnt matter for Anime really) but it handles Metadata alot better than Plex aswell as having much more room for the plugins.
the Clients support could be better, but its getting there (half a year ago it was ALOT worse)

**Comment by maxpiva** [comment]
Hmm. You keep me thinking. What about a little program, that ask for JMM Server IP, and generate the preferences. (Must be run on the machine where Plex Server is installed).

**Comment by AreFinstad** [comment]
well if that can be done then it sure would fix alot of things, just have it in the tutorial for the plugin install to tell people to use it before using the plugin and its good to go.... tho most people would prob have the Plex and JMM server on the same machine tho.

**Comment by AreFinstad** [comment]
got me thinking a bit aswell, why would we need another program? cant we build it into JMM desktop and let it output whatever file we need?

**Comment by CatmanIX** [comment]
My default user isn't named "Default" because i did indeed once have multiple users, I just don't anymore. And I don't want the Plex plugin using my default profile anyway (I'm setting this up for communal use in the living room). I'll see if renaming the guest user "User 3" will help.

Wouldn't the better solution to the whole thing be just having it as a text input box rather than a drop down? presumably, you know the name of the profile you want to connect to.

**Comment by CatmanIX** [comment]
(Ideally, i'd like to just have a Kodi plugin so i don't have to faff about with Plex >_>)
