### ISSUE TITLE
Plex not syncing watch status back to JMM

### ISSUE THREAD

**Issue by anzerman** [japanesemediamanager/plexplugin#17]
The plex plugin does not seem to update the watch status on JMM after finishing an episode. not sure what logs to post.. would you need both plex and jmm?

**Comment by AreFinstad** [comment]
logs for the server and the plex plugin would be nice.
at \Plex Media Server\Logs\PMS Plugin Logs\com.plexapp.plugins.myanime.log

can also confirm this @maxpiva happens here aswell. atleast in the plex server browser site.

**Comment by jmediamanager** [comment]
Pretty sure this is impossible

**Comment by anzerman** [comment]
ouch

**Comment by AreFinstad** [comment]
the Anime3 plugin for Media Portal v1 works, a bit unsure about the Anime Buddy works that way tho.
on a note on the plex plugin, would it be possible to let JMMS/D to track what gets streamed to the Plex Plugin and then have a list of it in JMMD? there the user can change the watchstates of what have been streamed if he has finished it and so on. ofc a way to clear the list is also needed in such a case.

**Comment by maxpiva** [comment]
Well te main problem, is plex do not support that feature for channels. The plugin in fact do not recieve watch/unwatch calls, it migtht recieve the rating in the future, since that is implemented in plex. Currently the channel part in plex is a hacking mess. It'll probably helps if the plex developers, get their plan together for the channels, but i think they are more interested in getting more users, and more devices, first.  

I tought it maybe feasible to implement a watch when plex read at least 95% of the episode. But since there is a transcoder in between 'sometimes', we could get false positives, since the transcoder is ahead of what we're watching.

**Comment by jmediamanager** [comment]
This app for Humminbird, might have some of the answers
https://forums.hummingbird.me/t/mac-hachidori-open-source-hummingbird-scrobbler-for-os-x/16952

Supports scrobbling for Plex, Crunchroll etc

**Comment by maxpiva** [comment]
Hmm, i think the objetive of the program is detect what you're watching,
via plex, crunchyroll, netflix, etc. and scrobble it. (Get metadata from
humminbird).
no the other way around.

**Comment by jmediamanager** [comment]
Oh I meant that if it can detect what you are watching it means that JMM could also detect what you are watching, and then sync watched states using that info.

**Comment by AreFinstad** [comment]
hmmm but how does plugins like the Trakt Plugin for Plex work then? doesnt that send a signal to the Trakt site? cant we have the JMM plugin send a signal to the JMM Server the same way kinda?

i know you guys have prob thought about this...... still wanted to share XD

**Comment by maxpiva** [comment]
Well, we know, what the user is watching, that for sure, since it'll trigger the filestream (JMM will provide the stream in question for the transcoder, or directly to the plex user). The problem is knowing when the user really watch the complete episode. We COULD trigger the watch status when 90% of the file es read or crossed. But as i said, before, the transcoder in plex may trick us, since is reading ahead of playing. Anyway we could explore the option as experimental.
