### ISSUE TITLE
Large library won't load.

### ISSUE THREAD

**Issue by Hakker** [japanesemediamanager/plexplugin#19]
The plex plugin doesn't seem to like 3400 titles in the list. The plugin just seem to silently time out. The "all" tile nicely says it has 3400 titles but when you click it then it just keeps loading indefinitely.

**Comment by maxpiva** [comment]
Currently i'm doing an update to JMMServer (#that will add contract caching on the db, which means, Asking for the whole library, will take less time, since they're less requests, less calculations, and less db roundtrips. (japanesemediamanager/jmmserver#257). Till will help out timeouts, on big collections, anyway, you have to undertstand that the volume of data is big, on big collection a bigger server capabilities will help.
